/**
 * Outbound-only Telegram sender.
 *
 * Direct POST to `https://api.telegram.org/bot<token>/sendMessage`. This is
 * the entire surface of Telegram in synthesis-worker — the bot infrastructure
 * lives in a future `artifacts/telegram-bot/` prompt.
 *
 * Failure handling: returns `{ ok: false, error }` on any HTTP error,
 * non-`ok: true` Telegram body, or thrown fetch error. **Never throws** —
 * Telegram preview failures must not abort a run whose persistence and
 * Inngest event have already succeeded.
 */

import type { TelegramSendResult } from './types.js';

export interface SendTelegramPreviewOptions {
  token: string;
  chatId: string;
  message: string;
  /** Injectable for tests. Defaults to the global `fetch`. */
  fetchFn?: typeof fetch;
  /** Parse mode passed to Telegram. Defaults to `'HTML'` per the spec. */
  parseMode?: 'HTML' | 'Markdown' | 'MarkdownV2';
}

interface TelegramApiBody {
  ok?: boolean;
  description?: string;
  error_code?: number;
}

export async function sendTelegramPreview(
  opts: SendTelegramPreviewOptions,
): Promise<TelegramSendResult> {
  const fetchFn = opts.fetchFn ?? fetch;
  const parseMode = opts.parseMode ?? 'HTML';
  const url = `https://api.telegram.org/bot${opts.token}/sendMessage`;

  try {
    const response = await fetchFn(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        chat_id: opts.chatId,
        text: opts.message,
        parse_mode: parseMode,
      }),
    });

    let body: TelegramApiBody | null = null;
    try {
      body = (await response.json()) as TelegramApiBody;
    } catch {
      body = null;
    }

    if (!response.ok) {
      const desc = body?.description ?? `HTTP ${response.status}`;
      return { ok: false, error: `Telegram sendMessage failed: ${desc}` };
    }
    if (body && body.ok !== true) {
      const desc = body.description ?? 'unknown';
      return { ok: false, error: `Telegram returned ok=false: ${desc}` };
    }
    return { ok: true, error: undefined };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { ok: false, error: `Telegram fetch error: ${message}` };
  }
}

/**
 * Defensively escape the small set of characters Telegram's HTML parse mode
 * treats specially. The title is generated by Claude Sonnet and could
 * theoretically contain `<`, `>`, or `&`.
 */
export function escapeTelegramHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

export interface PreviewMessageParts {
  title: string;
  pillar: string;
  signalCount: number;
}

export function buildPreviewMessage(parts: PreviewMessageParts): string {
  const safeTitle = escapeTelegramHtml(parts.title);
  const safePillar = escapeTelegramHtml(parts.pillar);
  return [
    '🗂 This week&#39;s article candidate',
    '',
    `Title: ${safeTitle}`,
    `Pillar: ${safePillar}`,
    `Signals clustered: ${parts.signalCount}`,
    '',
    'Interview starts Monday morning.',
  ].join('\n');
}

export function buildNoSignalsMessage(): string {
  return 'No capture signals found for synthesis this week. Check that ingestion jobs are running.';
}

export function buildNoQualifyingClustersMessage(): string {
  return 'Synthesis found no qualifying clusters this week. Consider adding more capture signals or lowering the threshold.';
}
